name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8 #changing python version from 3.10 to 3.8 to see if it fixes the error
  - pandas=2.0.3 #changing the pandas versionf rom 2.1.3 to see if it fixes version error
  - pytest=6.2.2
  - scipy #removing version number 1.5.2 to see if that fixes the error
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
